name: ML_poly
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.13
  - jupyterlab=3.3.4
  - pandas=1.4.2
  - numpy=1.22.3
  - scikit-learn=1.0.2
  - scipy=1.8.0
  - rdkit=2020.09.5
  - pytorch=1.11.0
  - pickleshare=0.7.5
  - cudatoolkit=11.3.1